remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme #
title: [The Artistry of Data and Technology]
description: [Reflecting on my digital humanities experience throughout Fall 2024.]
